services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    container_name: frontend-cnt
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules 
    command: npm run dev -- --host
